### ISSUE TITLE
想询问一下11.0.1还是使用的是py3.9吗，不知道为什么源码出现了报错

### ISSUE THREAD

**Issue by Nemo0223** [ZeroRin/GF_Theater_Commander#15]
![C9RP7ZUKQA_FILNQ)UDEGM2](https://github.com/gf-data-tools/GF_Theater_Commander/assets/75009684/a90eb321-face-4510-a60b-cc01cf3fff18)

**Comment by ZeroRin** [comment]
https://peps.python.org/pep-0622/

**Comment by Nemo0223** [comment]
感谢大佬，可以运行计算了，但是还遇到了一个问题就是枪械以及装备好像显示的是乱码，想问一下是要改一下读入相关文件的编码格式吗
![S3H}841OG7%)58H(SR8 WH5](https://github.com/gf-data-tools/GF_Theater_Commander/assets/75009684/0bebbc64-5519-44c6-9345-afdee5c840f0)
