### ISSUE TITLE
UnicodeDecodeError: 'gbk' 

### ISSUE THREAD

**Issue by Caeures** [ZeroRin/GF_Theater_Commander#2]
Hi, I got this kind of problem, the GFAlarm only output UTF-8. Is there any proxy can output GBK? Or other method to fix it?

```
C:\Users\User\Desktop\GF_Theater_Commander>main.exe 814

Traceback (most recent call last):
  File "main.py", line 28, in <module>
  File "utils.py", line 35, in load_info
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 160: illegal multibyte sequence
[2964] Failed to execute script main
```

**Comment by Caeures** [comment]
Nvm, I re export a UTF-8 user jason by GFAlarm and the problem magically fixed.
The UnicodeDecodeError: 'gbk' never appeared. I think it's the GFAlarm's export problem not yours.

**Comment by ZeroRin** [comment]
The problem here is that I am getting gbk outputs from GFAlarm and did not find a way to let it output utf-8 automatically.  I assume that it's related to different game server or something. In the latest commit i tried to ignore every non-ascii characters, hope it will solve the problem
