### ISSUE TITLE
減少調用LpAffineExpression.__init__的次數?

### ISSUE THREAD

**Issue by woofsauce** [ZeroRin/GF_Theater_Commander#3]
你好

我試了一下改用LpAffineExpression()和list批量建立 LpAffineExpression
在846 -m 25 -f 2下可以把計算所需的時間從25秒降到18秒左右

我另外也測試了幾個不同作戰區域，計算出的結果和未改動前一樣
不過改動候用LpProblem.toJson()導出的JSON比原本的還稍微大了一些，所以想請問有甚麼適合的方法來驗證LpProblem的內容
(50+MB的JSON....)
https://github.com/woofsauce/GF_Theater_Commander/commit/6c08ddc240976379a206e2f0db58d9e77d32110f

**Comment by ZeroRin** [comment]
也许调用wirteLP对比.lp更靠谱一些，但感觉还是会挺麻烦

**Comment by woofsauce** [comment]
之前witeLP()和writeMPS()都報錯，後來才注意到pulp不喜歡非ASCII的"强化资源"/"强化"。
文檔變大的原因是因為LpVariable.dicts()會強制在前頭加上"_"，然後LpVariable.dicts()本身好像也沒帶來什麼好處。

**Comment by ZeroRin** [comment]
其实不是不喜欢非ascii，是因为windows下open文件默认的编码不是utf8，导致往里写utf8符号就炸了。我之前把pulp这几个函数里的open全加上了encoding指定
