### ISSUE TITLE
linux 系统运行错误

### ISSUE THREAD

**Issue by WatermelonRei** [ZeroRin/GF_Theater_Commander#8]
`lp_bin = os.path.join(
        os.getcwd(),'solverdir\\cbc',
        lp.operating_system,lp.arch,
        lp.LpSolver_CMD.executableExtension('cbc')
    )`
lp求解器路近里使用的是windows的路径分隔符，其他系统下可能会报错
建议改为
`lp_bin = os.path.join(
        os.getcwd(),'solverdir','cbc',
        lp.operating_system,lp.arch,
        lp.LpSolver_CMD.executableExtension('cbc')
    )`

solverdir/cbc/linux 下的cbc文件没有赋予执行权限，跑起来会报错

**Comment by ZeroRin** [comment]
前者我改成用pathlib处理路径了，后者我不懂咋解决

**Comment by WatermelonRei** [comment]
https://blog.jdriven.com/2016/12/make-git-files-executable/

试一下这个？我也不确定
`
git update-index --chmod=+x solverdir/cbc/linux/64/cbd
`
`
git update-index --chmod=+x solverdir/cbc/linux/32/cbd
`

**Comment by WatermelonRei** [comment]
已经确认执行权限问题解决了
